[bouqueau] fix android build for script execution
git-svn-id: http://svn.code.sf.net/p/gpac/code/trunk/gpac@3163 63c20433-aa62-49bd-875c-5a186b69a8fb

diff --git a/build/android/jni/gpac_build_android b/build/android/jni/gpac_build_android
--- a/build/android/jni/gpac_build_android
+++ b/build/android/jni/gpac_build_android
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/bin/bash -e
 
 echo -e "\033[32m Note: You have to install Android NDK and setup the environment first!\033[0m"
 echo -e "\033[32m Note: You have to compile extra_libs first!\033[0m"
@@ -12,11 +12,13 @@ fi
 if [ -z "$2" ] 
 then 
   echo -e "\033[34m Usage: $0 PATH_TO_ANDROID_SDK : You have not give the directory path of SDK. Auto build of Osmo4.apk not possible. Build it with Eclipse \033[0m" 
+  exit 1
 fi 
 	 	 
 if [ -z "$3" ] 
 then 
   echo -e "\033[34m Usage: $0 PATH_TO_ANT : You have not give the directory path of ANT. Auto build of Osmo4.apk not possible. Build it with Eclipse \033[0m" 
+  exit 1
 fi 
 	 	 
 export PATH="$1:$PATH"
@@ -26,31 +28,30 @@ shift
 
 # Be sure to resolve if script not called from its directory
 export BUILDPATH=$(dirname "$0")
-cd $BUILDPATH || exit 1
+cd $BUILDPATH
 export BUILDPATH=$(pwd)
 echo "Current Dir = $BUILDPATH"
 version=$(svnversion)
 echo "*** Build path is $BUILDPATH, setting revision number $version"
-grep "$version" ../../../include/gpac/version.h 1>/dev/null && echo "Version $version already set" || echo "#define GPAC_SVN_REVISION \"$version\"" > ../../../include/gpac/version.h || exit 1
+grep "$version" ../../../include/gpac/version.h >/dev/null 2&>1 && echo "Version $version already set" || echo "#define GPAC_SVN_REVISION \"$version\"" > ../../../include/gpac/version.h
 echo "Building lib gpac ..."
-mkdir ../../../bin/android 2>/dev/null
-cd ../../../ || exit 1
+cd ../../../
 BASEPATH=$(pwd)
 
 rm -rf $BUILDPATH/../obj/local/armeabi/* || mkdir $BUILDPATH/../obj/local/armeabi
 rm -rf $BUILDPATH/../obj/local/armeabi-v7a/* || mkdir $BUILDPATH/../obj/local/armeabi-v7a
 
 
-cd $BUILDPATH || exit 1
+cd $BUILDPATH
 echo -n "Buiding all libs from $BUILDPATH..."
-ndk-build $* && echo "[OK] build successful." || echo "Build FAILED" || exit 1
+ndk-build $* && echo "[OK] build successful." || echo "Build FAILED"
 
 #echo "Copying modules to modules dir..."
-cd ../libs/ || exit 1
+cd ../libs/
 #for i in $(find . -name 'gm*.so')
 #do
 #	echo -n "$i..."
-#	cp "$i" "$BASEPATH/applications/osmo4_android/res/raw/" || exit 1
+#	cp "$i" "$BASEPATH/applications/osmo4_android/res/raw/"
 #done
 #echo
 #echo "[OK] success." 
@@ -60,7 +61,7 @@ echo "Copying libs to libs dir $LIBS_DIR ..."
 for i in $(find . -name '*.so')
 do
 	echo -n "$i..."
-	cp "$i" "$LIBS_DIR/$i" || exit 1
+	cp "$i" "$LIBS_DIR/$i"
 done
 echo
 echo "[OK] success module for Osmo4."
@@ -71,42 +72,40 @@ echo "Copying libs to libs dir $LIBS_DIR ..."
 for i in $(find . \( -name '*.so' \) -a \( -name "*ft2*" -o -name "*edit*" -o -name "*libgpac.so*" -o -name "*jpeg*" -o -name "*js_osmo*" -o -name "*mp4box*" -o -name "*openjpeg*" -o -name "*png*" -o -name "*libz.*" \) )
 do
 echo "$i"
-cp "$i" "$LIBS_DIR/$i" || exit 1
+cp "$i" "$LIBS_DIR/$i"
 done
 echo
 echo "[OK] success module for MP4box."
 
 
 LIBS_DIR="$BASEPATH/applications/osmo4_android/libs/"
-cd "$BASEPATH/extra_lib/lib/android" || exit 1
+cd "$BASEPATH/extra_lib/lib/android"
 echo "Copying all extra libs to $LIBS_DIR ..."
-for i in $(find . -name '*.so')
+for i in $(find . \( -name '*.so' \) -a \( -name "*ft2*" -o -name "*edit*" -o -name "*libgpac.so*" -o -name "*jpeg*" -o -name "*js_osmo*" -o -name "*mp4box*" -o -name "*openjpeg*" -o -name "*png*" -o -name "*libz.*" \) )
 do
-	echo -n "$i..."
-	cp "$i" "$LIBS_DIR/$i" || exit 1
+echo "$i ::: $BASEPATH/extra_lib/lib/android ::: $LIBS_DIR"
+cp "$i" "$LIBS_DIR/$i"
 done
 echo "[OK] success extra lib for Osmo4."
 
 LIBS_DIR="$BASEPATH/applications/mp4box_android/libs/"
-cd "$BASEPATH/extra_lib/lib/android" || exit 1
+cd "$BASEPATH/extra_lib/lib/android"
 echo "Copying all extra libs to $LIBS_DIR ..."
 
 for i in $(find . \( -name '*.so' \) -a \( -name "*ft2*" -o -name "*edit*" -o -name "*libgpac.so*" -o -name "*jpeg*" -o -name "*js_osmo*" -o -name "*mp4box*" -o -name "*openjpeg*" -o -name "*png*" -o -name "*libz.*" \) )
 do
 echo "$i"
-cp "$i" "$LIBS_DIR/$i" || exit 1
+cp "$i" "$LIBS_DIR/$i"
 done
 echo "[OK] success extra lib MP4box."
 
-if [ -w "$3" ] && [ -w "$2" ] 
-then 
+echo "Self-updating project"
+android update project -p "$BASEPATH/applications/osmo4_android/"
+
 echo -e "\nBuiding Osmo4.apk" 
 cd $BASEPATH/applications/osmo4_android/
-ant release || exit 1
+ant release
 
-zipalign -v 4 bin/Osmo4-unaligned.apk bin/Osmo4.apk
+zipalign -v 4 bin/Osmo4-unaligned.apk $BASEPATH/Osmo4-$(grep "\#define GPAC_VERSION " $BASEPATH/include/gpac/tools.h | cut -d "\"" -f 2 )-r$version.apk
 rm bin/Osmo4-*
 echo -e "\n[OK] success."
-fi
-
-
