SOUCHAY ---- Huge changes : fixed several Double Free in lots of Modules. Android C library is far more strict about this causing lots of crashes / Added some interresting logs to discover from where the native code is running. Fixed Build for Android (no need to rebuild everything each time). Wrapper is now safer and can detect some cases where GPAC cannot initialize properly. Shutdowns nicely GPAC when quitting activity. Added ability to launch GPAC ANdroid from Android Brower (or mail...) using Intent filters
git-svn-id: http://svn.code.sf.net/p/gpac/code/trunk/gpac@2822 63c20433-aa62-49bd-875c-5a186b69a8fb

diff --git a/build/android/jni/gpac_build_android b/build/android/jni/gpac_build_android
--- a/build/android/jni/gpac_build_android
+++ b/build/android/jni/gpac_build_android
@@ -29,7 +29,7 @@ BINPATH=$(pwd)
 
 cd $BUILDPATH || exit 1
 echo -n "Buiding all libs from $BUILDPATH..."
-ndk-build && echo "OK build successful" || (echo "Build FAILED" ; exit 1)
+ndk-build && echo "OK build successful" || echo "Build FAILED" || exit 1
 
 echo "Copying libs to $BINPATH..."
 cp  ../libs/armeabi/libgpac.so ../libs/armeabi/libjavaenv.so  $BINPATH || exit 1
@@ -44,7 +44,7 @@ done
 echo "Building gpac wrapper..."
 
 cd $BASEPATH/applications/osmo4_android || exit 1
-ndk-build 
+ndk-build && echo "Wrapper built successfully" || echo "Build failed for Wrapper" || exit 1
 
 echo "Copying libs from $BASEPATH/extra_lib/lib/android to $BASEPATH/applications/osmo4_android/libs/armeabi ..."
 
