Fixed many issues with JNI thread safety, still has some issues. Now when a module does not work, it should be possible to diagnose why. Fixed android buid. Now only uses ndk-make. The shell script build/android/jni/gpac_build_android only copies libs now
git-svn-id: http://svn.code.sf.net/p/gpac/code/trunk/gpac@2888 63c20433-aa62-49bd-875c-5a186b69a8fb

diff --git a/build/android/jni/gpac_build_android b/build/android/jni/gpac_build_android
--- a/build/android/jni/gpac_build_android
+++ b/build/android/jni/gpac_build_android
@@ -25,37 +25,30 @@ echo "Building lib gpac ..."
 mkdir ../../../bin/android 2>/dev/null
 cd ../../../ || exit 1
 BASEPATH=$(pwd)
-cd bin/android || exit 1
-BINPATH=$(pwd)
 
 cd $BUILDPATH || exit 1
 echo -n "Buiding all libs from $BUILDPATH..."
-ndk-build $* && echo "OK build successful" || echo "Build FAILED" || exit 1
+ndk-build $* && echo "[OK] build successful." || echo "Build FAILED" || exit 1
 
-echo "Copying libs to $BINPATH..."
-cp  ../libs/armeabi/libgpac.so ../libs/armeabi/libjavaenv.so  $BINPATH || exit 1
-
-echo "Renaming modules and copying modules to $BINPATH..."
-cd ../libs/armeabi || exit 1
-for fn in libgm*.so
+echo "Copying modules to modules dir..."
+cd ../libs/ || exit 1
+for i in $(find . -name 'gm*.so')
 do
-	cp "$fn" "$BINPATH/${fn##lib}" || exit 1
+	echo -n "$i..."
+	cp "$i" "$BASEPATH/applications/osmo4_android/res/raw/" || exit 1
 done
+echo
+echo "[OK] success." 
 
-echo "Building gpac wrapper..."
-
-cd $BASEPATH/applications/osmo4_android || exit 1
-ndk-build $* && echo "Wrapper built successfully" || echo "Build failed for Wrapper" || exit 1
-
-echo "Copying libs from $BASEPATH/extra_lib/lib/android to $BASEPATH/applications/osmo4_android/libs/armeabi ..."
-
-cd $BASEPATH/extra_lib/lib/android || exit 1
-for fn in *.so; do
-	cp $fn $BASEPATH/applications/osmo4_android/libs/armeabi
+LIBS_DIR="$BASEPATH/applications/osmo4_android/libs/"
+echo "Copying libs to libs dir $LIBS_DIR ..."
+for i in $(find . -name 'lib*.so')
+do
+	echo -n "$i..."
+	cp "$i" "$LIBS_DIR/$i" || exit 1
 done
-
-echo "Copying all libs to $BASEPATH/applications/osmo4_android/libs/armeabi..."
-cp $BINPATH/lib*.so $BASEPATH/applications/osmo4_android/libs/armeabi || exit 1
-cp $BINPATH/gm*.so $BASEPATH/applications/osmo4_android/res/raw/ || exit 1
-
-#cp $BASEPATH/applications/osmo4_android/bin/*.apk $BINPATH || exit 1
+echo
+echo "[OK] success."
+echo "Copying all extra libs..."
+cp $BASEPATH/extra_lib/lib/android/lib*.so "$LIBS_DIR/armeabi/" || echo "FAILED"
+echo "[OK] success."
