last fixes for the distribution workflows

diff --git a/.github/workflows/dist-linux.yml b/.github/workflows/dist-linux.yml
--- a/.github/workflows/dist-linux.yml
+++ b/.github/workflows/dist-linux.yml
@@ -124,64 +124,74 @@ jobs:
           passphrase: ${{ secrets.GPG_PASSPHRASE }}
           trust_level: 5 # ultimate
 
+      - uses: ruby/setup-ruby@v1
+        with:
+          ruby-version: '3.4'
+          bundler-cache: true
+
       - name: Install deb-s3
         run: gem install deb-s3
 
       - name: Publish the artifacts
         shell: bash
         run: |
-          set -euo pipefail
+          set -euxo pipefail
           shopt -s nullglob
 
-          for file in artifacts/*.deb; do
-            echo "Adding artifact $artifact to $S3_BUCKET repository."
+          for folder in artifacts/*; do
+            echo "Processing folder $folder"
 
-            # Rename the artifact so that there is no conflict
-            if [[ $artifact == *.deb ]]; then
-              folder_name=$(basename "$(dirname "$artifact")")
+            for artifact in "$folder"/*; do
+              echo "Adding artifact $artifact to ${{ secrets.DIST_S3_BUCKET }} repository."
 
-              # Extract the required parts from the folder name
-              if [[ $folder_name =~ linux-([^-]+)-[^-]+-([^-]+)-([^-]+)@([^-]+) ]]; then
-                component="${BASH_REMATCH[1]}"
-                distro="${BASH_REMATCH[2]}"
-                codename="${BASH_REMATCH[3]}"
-                arch="${BASH_REMATCH[4]}"
-                date=$(date +"%s%3N")
+              # Rename the artifact so that there is no conflict
+              if [[ $artifact == *.deb ]]; then
+                folder_name=$(basename "$(dirname "$artifact")")
 
-                # Get the version from the artifact name
-                file_name=$(basename "$artifact")
-                identifier=$(echo "$file_name" | cut -d'-' -f1) # gpac or libgpac
+                # Extract the required parts from the folder name
+                if [[ $folder_name =~ linux-([^-]+)-[^-]+-([^-]+)-([^-]+)@([^-]+) ]]; then
+                  component="${BASH_REMATCH[1]}"
+                  distro="${BASH_REMATCH[2]}"
+                  codename="${BASH_REMATCH[3]}"
+                  arch="${BASH_REMATCH[4]}"
+                  date=$(date +"%s%3N")
 
-                # Create a new name for the artifact
-                new_name="${identifier}_${component}_${distro}_${codename}_${arch}_${date}.deb"
+                  # Get the version from the artifact name
+                  file_name=$(basename "$artifact")
+                  identifier=$(echo "$file_name" | cut -d'-' -f1) # gpac or libgpac
 
-                # Copy the artifact to a new file with the new name
-                cp "$artifact" "${{ runner.temp }}/$new_name"
+                  # Create a new name for the artifact
+                  new_name="${identifier}_${component}_${distro}_${codename}_${arch}_${date}.deb"
 
-                # Upload the artifact with the new name
-                deb-s3 upload \
-                  ${{ runner.temp }}/$new_name \
-                  --bucket ${{ secrets.DIST_S3_BUCKET }} \
-                  --endpoint ${{ secrets.DIST_S3_ENDPOINT }} \
-                  --sign "${{ steps.import-gpg.outputs.keyid }}" \
-                  --prefix linux/$distro/ \
-                  --component $component \
-                  --codename $codename \
-                  --arch $arch \
-                  --origin https://dist.gpac.io \
-                  --preserve-versions
-                echo "Uploaded $new_name to ${{ secrets.DIST_S3_BUCKET }}/linux/$distro/"
+                  # Copy the artifact to a new file with the new name
+                  cp "$artifact" "${{ runner.temp }}/$new_name"
+
+                  # Upload the artifact with the new name
+                  deb-s3 upload \
+                    ${{ runner.temp }}/$new_name \
+                    --bucket ${{ secrets.DIST_S3_BUCKET }} \
+                    --endpoint ${{ secrets.DIST_S3_ENDPOINT }} \
+                    --sign "${{ steps.import-gpg.outputs.keyid }}" \
+                    --prefix linux/$distro/ \
+                    --component $component \
+                    --codename $codename \
+                    --arch $arch \
+                    --origin https://dist.gpac.io \
+                    --lock \
+                    --preserve-versions
+                  echo "Uploaded $new_name to ${{ secrets.DIST_S3_BUCKET }}/linux/$distro/"
+                else
+                  echo "Invalid folder name format: $folder_name"
+                  exit 1
+                fi
               else
-                echo "Invalid folder name format: $folder_name"
+                echo "Artifact must be a .deb file: $artifact"
                 exit 1
               fi
-            else
-              echo "Artifact must be a .deb file: $artifact"
-              exit 1
-            fi
+            done
           done
 
       - name: Upload the public key
         run: |
           gpg --armor --export "${{ steps.import-gpg.outputs.fingerprint }}" > gpg.asc
-          aws s3 cp gpg.asc s3://${{ secrets.DIST_S3_BUCKET }}/linux/gpg.asc --endpoint-url ${{ secrets.DIST_SECRET_ENDPOINT }}
+          aws s3 cp gpg.asc s3://${{ secrets.DIST_S3_BUCKET }}/linux/gpg.asc --endpoint-url ${{ secrets.DIST_S3_ENDPOINT }}
